name: resolve-packages
on:
  push:
    branches: [ master ]    
  pull_request:
    branches: [ master ]
jobs:
  resolvePackageDependencies:
    runs-on: [self-hosted, macOS]    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Resolve package dependencies 
      run: xcodebuild -resolvePackageDependencies -workspace Nimble.xcworkspace -scheme Nimble-Release     
